trigger:
  - master
  - task: Npm@1
    inputs: null
    command: install
pool:
  vmImage: ubuntu-latest
steps:
  - script: 'echo Hello, world!'
    displayName: Run a one-line script
  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: Run a multi-line script
  - task: CmdLine@2
    inputs:
      script: |
        echo running LoginTest

        npx playwright test  SupplierPortal.test.ts